name: 'filters-pr-checker'
description: 'Checks filters pull requests'
inputs:
  repo-token:
    description: 'github token'
    required: true
  test:
    description: 'test'
    required: true
  test-dash:
    description: 'test-dash'
    required: true
runs:
  using: 'composite'
  steps:
    - name: 'Install dependencies'
      run: yarn install
      shell: 'bash'
    - name: 'Run action'
      run: node dist/index.js
      shell: bash
      env:
        REPO_TOKEN: ${{ inputs.repo-token }}
