name: 'filters-pr-checker'
description: 'Checks filters pull requests'
inputs:
  repo-token:
    description: 'github token'
    required: true
runs:
  using: 'composite'
  steps:
    - name: 'Install dependencies'
      run: yarn install
      shell: 'bash'
    - name: 'Run action'
      run: node dist/index.js ${{ inputs.repoToken }}
      shell: 'bash'
